### ISSUE TITLE
Humoi's survey size limits

### ISSUE THREAD

**Issue by InariTheKitsune** [Humoiww/BDCC_NanoRevolution_MOD#1]
Humoi's survey size limits don't go above 1 inch

Question 3:

Currently our android visible component size range is:

Minimum Penis Length : 1 in
Maximum Penis Length : 1 in
Maximum Penis Length : 1 in
Maximum Penis Length : 1 in
Are you comfortable with this? If you'd like to adjust, please click "Edit" to make changes. Otherwise, click "Next" to proceed to the next question

Edit Max Cock: 11.81 in

Currently our android visible component size range is:

Minimum Penis Length : 1 in
Maximum Penis Length : 1 in
Maximum Penis Length : 1 in
Maximum Penis Length : 1 in

Expected Max Penis size to be 11.81 inches

Mods used
1) collar_newtown76.zip
2) JackalPartsVer2.zip
3) ChainsPoC.zip
4) ChastityCageFlat.zip
5) FluffbodypartsVer3.zip
6) LucarioSpecies-Ver2.1.zip
7) ProstheticPartsVer0.zip
8) AcesAvairyAddonVer0.99.zip
9) Chasitybeltmod.zip
10) DragonsPlusVer0.9.zip
11) Straitjacketmod.zip
12) MoreDrugsMod-v0.04a.zip
13) Stock_events__Rat_species.zip
14) AngularSkinConv.zip
15) IndustrialSkinConv.zip
16) LayeredSkinConv.zip
17) LongUniformVer1.zip
18) SabertoothHeadsVer1.zip
19) Clothes_Megapack.zip
20) AcesSharkSpeciesVer1.11.zip
21) EditedPawsVer1.zip
22) EditedSheathVer1.11.zip
23) PiercingsModVer0.9.zip
24) DickSkinsBatch2.zip
25) Laquine_SpeciesVer1.2.zip
26) Newdrugsv2.zip
27) PiercingsVer1.zip
28) SquirrelSpeciesVer0.9.zip
29) BarbedEquinePenisVer1.1.zip
30) DemonHoundConversionVer1.zip
31) PlusCombat_1.0.zip
32) SpinedDragonPenisVer1.zip
33) BovineSpeciesVer2.zip
34) SeahorseSpeciesVer0.9.zip
35) AcesWorldbuildingModVer0.3.zip
36) AnnouncerBDSM.zip
37) AmpwaveSpeciesVer0.9.zip
38) BreedableAvy.zip
39) MaleLactation.zip
40) Shark_Species.zip
41) BreedableAlex_-_Vanilla.zip
42) CharacterFlairVer1_-_BreedableAlex.zip
43) HoundoomSpeciesVer1.zip
44) n76-ultrapack.zip
45) HairSkinsBatch1.zip
46) KnottedEquinePenisVer3.zip
47) Vyk_Torso_Pump.zip
48) AcesProtogenMod-Ver1.1.zip
49) SynthModVer1.3.zip
50) AvaliSpeciesVer2.zip
51) DeerSpeciesVer2.1.zip
52) SergalSpeciesVer0.9.zip
53) ScalieExpansionVer2.1.zip
54) SkulldogSpeciesVer2.zip
55) TheFlameheartsV0.4.Alpha1.zip
56) LoonaMod.zip
57) AnnouncerBDSMArticaPatch.zip
58) AcePregExpacVer0.6-NovaSub.zip
59) LycanrocSpeciesVer0.9.zip
60) BreedableCheckpointGuard.zip
61) MoreUniformsVer5.zip
62) BatSpeciesVer0.9.zip
63) ImprovedCuffs.zip
64) BarbedandKnottedEquinePenis.zip
65) KnotFucking.zip
66) MoreBDSMstuff.zip
67) GooBondage.zip
68) LopunnySpeciesVer1.zip
69) SylveonSpeciesVer1.zip
70) TheFlameheartsV0.4.Alpha1.2.zip
71) CaninePussy.zip
72) ModsOptions.zip
73) EquinePussy.zip
74) LazyBulldogReplacer.zip
75) NanoRevolutionModv0.2.0.zip
76) HypertusR5-1.zip
77) HypertusSpeciesCompatibilityLayersR2.zip

**Comment by Humoiww** [comment]
Got it, may probably the unit problem, I've only test this in cm unit. Will check that later.

**Comment by Humoiww** [comment]
OK, not the unit problem, must be one of the mod cause this confliction, I will check that once I have more report regarding this. (Sorry, since 77 mods is too large for me to test them individually :(

**Comment by Humoiww** [comment]
Hi, I've update the v0.3.0 version, that should fix this issue, I will close issue now. But if you still meet same problem, feel free to reopen this issue owo!
