### ISSUE TITLE
Blueprint loss

### ISSUE THREAD

**Issue by Fox33m** [Humoiww/BDCC_NanoRevolution_MOD#4]
**Describe the bug**
The "General" blueprints get lost after reloading a game; the items you printed with them does not; the cores used for purchase the blueprints get lost

**To Reproduce**
I simply closed and opened the game, and the blueprint were lost; this happen also with quicksaves and quick loads

**Expected behavior**
Blueprints shouldn't disappears after reloading a save

**Screenshots**

**Other Mods:**
I am using several mods; but even disabling them the problem persist

(Note: If possible, it is very welcome for you to disable some mods and check which mod(s) lead this bug `~w~`)

**Comment by Humoiww** [comment]
Hi, just want to say thanks for this bug report. This bug has been fix in v0.3.1 update owo! If you still meet this problem in new version, feel free to reopen this issue!
