### ISSUE TITLE
No Hacking key

### ISSUE THREAD

**Issue by Fox33m** [Humoiww/BDCC_NanoRevolution_MOD#6]
Apparently you lost the ability to ask Alex about the key for hacking the robots, which blocks your possibility to hack them; I don't know if is linked at that, but you cannot ask him the datapad for Vion as well, but you can still interact with him (Vion) to complete his questline; you cannot ask Humoi the key anyway, so you cannot "claim" any robot

**To Reproduce**
Get the hack perk, start the questline, and talk to Alex

**Expected behavior**
You should be able to ask Alex the key, which he bounce you back to Humoi

**Comment by Humoiww** [comment]
Got it! Fix in 0.4.1
